### ISSUE TITLE
termination_criteria.EpochCounter with new_epochs=False does not check before running

### ISSUE THREAD

**Issue by cancan101** [lisa-lab/pylearn2#1078]
I am using `termination_criteria.EpochCounter` with `new_epochs=False` along with `monitor.push_monitor` with `transfer_experience=True`. The model loaded has already seen more than or equal to `max_epochs` but the main training loop still performs one epoch before terminating. 

This is a bug; no training should occur since we are at or exceeding `max_epochs`.

**Comment by hantek** [comment]
Hi I wrote a solution regarding this problem at #1428 . A continue_learning check is been done while the program enters the main_loop() function. So it only introduce on extra time of checking and doesn't change the order of training procedure.

Other midifications are adapted for this change and, new tests for zero epochs of training added.

**Comment by goodfeli** [comment]
Should we close this PR? It looks like it has been replaced by #1480. Or am I wrong about that?

**Comment by hantek** [comment]
I guess you mean to close #1428?
