### ISSUE TITLE
Make col_norm constraints a Model Extension

### ISSUE THREAD

**Issue by lamblin** [lisa-lab/pylearn2#1128]
Follow-up from #190.
Should use the same mechanism @dwf is working on for #189

**Comment by goodfeli** [comment]
I did this already for maxout: https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/models/maxout.py#L172

The only remaining work is to replace max_col_norm implementations in other models with calls to the same ModelExtension.

**Comment by lamblin** [comment]
The rest was done in #1484.
