### ISSUE TITLE
Mean pooling

### ISSUE THREAD

**Issue by zuheli** [lisa-lab/pylearn2#1137]
## Then I tried to change the pool_type in the init function(def **init**) of pylearn2.models.mlp.ConvRectifiedLinear. The traning went on for one epoch,and the error was as follows:

Exception                                 Traceback (most recent call last)
<ipython-input-2-a29d25125a51> in <module>()
      1 from pylearn2.config import yaml_parse
      2 train = yaml_parse.load(train)
----> 3 train.main_loop()

/home/nwpu/pylearn2/pylearn2/train.pyc in main_loop(self, time_budget)
    215                             break
    216
--> 217                         rval = self.algorithm.train(dataset=self.dataset)
    218                     if rval is not None:
    219                         raise ValueError("TrainingAlgorithm.train should not "

/home/nwpu/pylearn2/pylearn2/training_algorithms/sgd.pyc in train(self, dataset)
    484             value = param.get_value(borrow=True)
    485             if not isfinite(value):
--> 486                 raise Exception("NaN in " + param.name)
    487
    488     def continue_learning(self, model):

Exception: NaN in h2_W

**Comment by lamblin** [comment]
- using `pool_type='mean'` in a YAML file makes the YAML parser interpret that as one keyword, which is unknown. @dwf are you proposing that we look for `=` in keywords, and add a specific error message in that case?
- @zuheli the `NaN` are probably due to you using a learning rate that is too high.
