### ISSUE TITLE
First model in the MLP tutorial is fit with BGD, tutorial says it is SGD

### ISSUE THREAD

**Issue by lendle** [lisa-lab/pylearn2#1152]
See [here](https://github.com/lisa-lab/pylearn2/blob/d1e457664935a4466e906bd2eb6e35ced1f7b151/pylearn2/scripts/tutorials/multilayer_perceptron/mlp_tutorial_part_2.yaml#L22)

The other two models are fit with SGD as advertised. I discovered this when trying to figure out why the first model takes 10x longer per epoch than the others.

**Comment by lamblin** [comment]
The current version mentions BGD for the softmax regression, so I think it has been fixed.
