### ISSUE TITLE
data_specs and return_tuple parameters are missing from abstract Dataset class

### ISSUE THREAD

**Issue by gaa-cifasis** [lisa-lab/pylearn2#1266]
The parameters data_specs and return_tuple in iterator method are missing from abstract Dataset class. Exactly [here](https://github.com/lisa-lab/pylearn2/blob/13497cc8fc6b8c5029ebb6e81d5264d18058e655/pylearn2/datasets/dataset.py#L20)

**Comment by lamblin** [comment]
Done in gh-1386.
