### ISSUE TITLE
Bug in FlattenerLayer.get_layer_monitoring_channels

### ISSUE THREAD

**Issue by pikqu** [lisa-lab/pylearn2#1301]
Problem is that when raw_space in this function is composite space:
raw_space CompositeSpace(Conv2DSpace(shape=(4, 4), num_channels=64, axes=('c', 0, 1, 'b'), dtype=float32), Conv2DSpace(shape=(4, 4), num_channels=64, axes=('c', 0, 1, 'b'), dtype=float32), Conv2DSpace(shape=(4, 4), num_channels=64, axes=('c', 0, 1, 'b'), dtype=float32), Conv2DSpace(shape=(4, 4), num_channels=64, axes=('c', 0, 1, 'b'), dtype=float32), Conv2DSpace(shape=(4, 4), num_channels=64, axes=('c', 0, 1, 'b'), dtype=float32))
and raw_state:
raw_state (Reshape{2}.0, Reshape{2}.0, Reshape{2}.0, Reshape{2}.0, Reshape{2}.0)
and inside function when you execute code line:
raw_space.validate(raw_state)
you get error:
ValueError: The value of a Conv2DSpace batch must be 4D, got 2 dimensions for Reshape{2}.0.
Bug started with commit: cb6b2510af7f607f729822f8bddc54cace5864cf

**Comment by JesseLivezey** [comment]
I started working on a undo_format_as option  here:
https://github.com/lisa-lab/pylearn2/pull/1337

It is still very untested.

**Comment by JesseLivezey** [comment]
FYI, I think I've fixed this in #1337, but I still need to clean it up and write tests.
