### ISSUE TITLE
Misleading termination criteria "And" and "Or"

### ISSUE THREAD

**Issue by riga** [lisa-lab/pylearn2#1311]
The naming of the termination criteria "And" and "Or" is quite misleading.

When I think of a criterion that terminates the training, I expect an *Or operator* to decide to stop if one of its criteria decides to stop and vice versa for the *And operator*. Since you name them **Termination**Criterion while using ``any`` and ``all`` to accumulate their **continue**_learning responses, the above terminology is pretty confusing. (I think it's really the **Termination** vs. **continue** part).

**Comment by lamblin** [comment]
See #1405 for a solution.
