### ISSUE TITLE
Allow border_mode to be a tuple

### ISSUE THREAD

**Issue by cancan101** [lisa-lab/pylearn2#1325]
Currently the underlying convolution operators support passing a tuple of paddings (see: http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html#theano.sandbox.cuda.dnn.dnn_conv). 

Ideally support passing the a tuple for `border_mode` through. Or at the very least support `border_mode='half'`.

**Comment by lamblin** [comment]
I'm not sure what the current status is. @nouiz can you comment?

**Comment by nouiz** [comment]
it is done.
