### ISSUE TITLE
Add "minimum epoch number to save" functionality to MonitorBasedSaveBest

### ISSUE THREAD

**Issue by dwf** [lisa-lab/pylearn2#1344]
Basically, if you know that you aren't going to encounter your SOTA result before epoch 200, you shouldn't waste time pickling your model.

**Comment by JesseLivezey** [comment]
A slightly more flexible version that I've started to use recently is:
- save best model at most every N epochs
- until epoch M, then always save best model

**Comment by dwf** [comment]
Sounds good to me. CC @hantek, who is assigned this ticket.
