### ISSUE TITLE
compute_test_err.py is broken for mnist.yaml in maxout

### ISSUE THREAD

**Issue by JesseLivezey** [lisa-lab/pylearn2#1354]
This line:
https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/scripts/papers/maxout/compute_test_err.py#L55
will fail because x_arg will already be in a Conv2D space for mnist.yaml.

See discussion here:
https://groups.google.com/forum/#!topic/pylearn-users/WAo8x3LzvdU

**Comment by lamblin** [comment]
That's correct, lines 54 and 55 should be removed, because the iterator is already doing the conversion.
