### ISSUE TITLE
test_convnet.py from tutorials fails on Windows

### ISSUE THREAD

**Issue by Pastafarianist** [lisa-lab/pylearn2#1385]
[`pylearn2/pylearn2/scripts/tutorials/convolutional_network/tests/test_convnet.py`](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/scripts/tutorials/convolutional_network/tests/test_convnet.py) fails on Windows, since the YAML parser assumes that backslashes in `save_path` mean escaped characters. A possible dirty fix to make this particular test pass is to add the following line:

    save_path = save_path.replace('\\', '/')

so that the file now reads as:

    yaml_file_path = os.path.abspath(os.path.join(os.path.dirname(__file__),
                                                  '..'))
    save_path = os.path.dirname(os.path.realpath(__file__))
    save_path = save_path.replace('\\', '/')

    yaml = open("{0}/conv.yaml".format(yaml_file_path), 'r').read()

**Comment by lamblin** [comment]
I would rather replace the `/` in `"{0}/conv.yaml"` by a call to `os.path.join`, so on Windows there would be only the native `\\`, rather than only `/`.
Would you be willing to submit a PR with that change?

**Comment by Pastafarianist** [comment]
@lamblin It won't help. `save_path` is directly substituted in YAML code in [line 36](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/scripts/tutorials/convolutional_network/tests/test_convnet.py#L36). If there are backslashes in `save_path`, the YAML parser will not be able to handle them.

**Comment by lamblin** [comment]
Oh, right, I misunderstood.
I'm wondering if we should use `save_path.replace('\\', r'\\')` instead, to keep Windows-style separators, but there is already an hardcoded `/` in the file.

**Comment by lamblin** [comment]
Done in #1418.
