### ISSUE TITLE
Supervised training problem in pylearn2/scripts/tutorials/deep_trainer/run_deep_trainer.py

### ISSUE THREAD

**Issue by jungle-cat** [lisa-lab/pylearn2#1427]
In the file  pylearn2/scripts/tutorials/deep_trainer/run_deep_trainer.py
line 270:    # supervised training
line 271:    layer_trainers[-1].main_loop()

the above lines are used for supervised training with layer_trainers[-1] being get_layer_trainer_logistic(layers[3], trainset[3]), so in the so called supervised training, I'm think that only the parameters of logsitic layer are updated, while the parameters of other layers (autoencoder/RBM) will remain unchanged.

Is this a bug ?

**Comment by lamblin** [comment]
It is true that only the parameters of the last (classification) layer's parameter is updated in that script.
It is just the way the model is set up: fine-tuning of the first layers by back-propagation is not necessary, although it usually gives better results.
If you are looking with examples with full fine-tuning, you can have a look at https://github.com/lisa-lab/pylearn2/tree/master/pylearn2/scripts/tutorials/stacked_autoencoders instead.

**Comment by jungle-cat** [comment]
OK, thank you for your help.
