### ISSUE TITLE
Improving mapping.nest error message

### ISSUE THREAD

**Issue by goodfeli** [lisa-lab/pylearn2#1450]
If you pass mapping.nest something that is a list rather than a tuple, you get a completely unrelated error message:

      File "/usr/local/google/home/goodfellow/pylearn2/pylearn2/utils/data_specs.py", line 273, in nest
        assert self.n_unique_specs == 1
    AssertionError

**Comment by goodfeli** [comment]
I don't really understand this portion of the codebase so @lamblin should probably comment on this.

**Comment by lamblin** [comment]
It would make sense to convert lists as tuples.
In general, what we want to detect is if "flat" is actually a single element that we want at different places in the nested tuple, and raise an exception if the mapping actually refers to more than one specs.
