### ISSUE TITLE
[enhancement] yaml_parser.py

### ISSUE THREAD

**Issue by TNick** [lisa-lab/pylearn2#1452]
Hello,
This message would probably be more suited to dev mailing list.
Please let me know if you are interested in a pull request for following issues:

------------------

[additional environment](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/config/yaml_parse.py#L18) that is passed to `yaml_parse.load()` and `yaml_parse.load_path()` is only used in 
[multi_constructor_pkl](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/config/yaml_parse.py#L378). As a result strings processed elsewhere (as normal string values, for example) will throw an exception if the key is not in the environment.
By replacing [this line ](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/config/yaml_parse.py#L167):
```python
 return preprocess(proxy)
```
with this
```python
 return preprocess(proxy, additional_environ)
```
those other strings would see the custom dictionary.

------------------

On a related issue, `!float` can be made aware of os/custom values by replacing [this part](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/config/yaml_parse.py#L420):
```python
 value = loader.construct_scalar(node)
 return float(value)
```
with this one:
```python
 value = loader.construct_scalar(node)
 return float(preprocess(value, additional_environ))
```
------------------

Still regarding the custom dictionary that can be passed to  `yaml_parse.load()` and `yaml_parse.load_path()`: right now the user must provide all values as strings because of the way `string_utils.preprocess()` works. One solution to this is to modify [load()](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/config/yaml_parse.py#L204):
```python
    # preprocess in string_utils assumes strings so we are making
    # all entries strings here
    if not environ is None:
        for k in environ.keys():
            environ[k] = str(environ[k])

    additional_environ = environ
```
thus allowing one to write
```python
environ = {'abcd': 1.1}
```
instead of
```python
environ = {'abcd': '1.1'}
```
A matter of taste, no doubt, just as my extensive use of code blocks. :)

**Comment by lamblin** [comment]
@dwf, would you mind having a look? I'm not really familiar with the YAML parser.

**Comment by TNick** [comment]
I just found [this thread](https://groups.google.com/forum/#!msg/pylearn-users/GuOMb_ZQy4M/T6ImXkM6Dp4J) ([last message](https://groups.google.com/d/msg/pylearn-users/GuOMb_ZQy4M/A-_W5-nuY-QJ)) that's probably related to this issue.

**Comment by TNick** [comment]
These things are implemented now in [TNick/pyl2extra](https://github.com/TNick/pyl2extra/blob/master/pyl2extra/config/yaml_parse.py).
Closing this issue.
