### ISSUE TITLE
[bug] _validate_impl for Conv2DSpace

### ISSUE THREAD

**Issue by TNick** [lisa-lab/pylearn2#1454]
[This line](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/space/__init__.py#L1968):
```python
        if isinstance(batch, theano.gof.Variable):
```
should be
```python
        if not is_numeric:
```
right?

**Comment by lamblin** [comment]
Yes, that would make more sense.

**Comment by TNick** [comment]
pull request #1455
