### ISSUE TITLE
make pickle data target

### ISSUE THREAD

**Issue by jeehye** [lisa-lab/pylearn2#1473]
Hello
I try to make pickle file with data and target.
One of my feature is consist of [data, target].
data is 2x33x40 numpy array, and target is 1 numpy array.
But when I tried to run code with this pickle file, I got error in target shuffle part.
numpy.random.shuffle(data)
numpy.random.shuffle(target)

File "mtrand.pyx", line 4424, in mtrand.RandomState.shuffle (numpy/random/mtrand/mtrand.c:21254)
TypeError: len() of unsized object

I think this error occured because target length and data length is different.
How can I change target array??

**Comment by TNick** [comment]
A traceback would be useful, at least for me.
There seem to be [a lot of reports](https://www.google.ro/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=mtrand.RandomState.shuffle+numpy%2Frandom%2Fmtrand%2Fmtrand+TypeError:+len()+of+unsized+object) regarding that error that may not be related to pylearn2.

**Comment by lamblin** [comment]
- Please use the mailing list (pylearn-users) for support requests, not tickets
- This is not related to Pylearn2 at all
