### ISSUE TITLE
PyrexScanner' object has no attribute 'position'

### ISSUE THREAD

**Issue by ever4cyth** [lisa-lab/pylearn2#1478]
File "/usr/local/lib/python2.7/site-packages/Cython-0.19.1-py2.7-linux-x86_64.egg/Cython/Compiler/Parsing.py", line 1916, in p_statement_list
    pos = s.position()
AttributeError: 'Cython.Compiler.Scanning.PyrexScanner' object has no attribute 'position'

How to solve this issue? according to another thread

That's because position() is compiled as a cdef method here:
https://github.com/cython/cython/blob/master/Cython/Plex/Scanners.pxd

**Comment by dwf** [comment]
You'll have to ask the Cython people. I've never seen that before.

**Comment by ever4cyth** [comment]
Thanks for your reply! Would you kindly tell me which version of cython you used to compile pylearn2? I used cython-0.19.
