### ISSUE TITLE
update_channel in live monitoring

### ISSUE THREAD

**Issue by alalbiol** [lisa-lab/pylearn2#1506]
pylearn2/train_extensions/live_monitoring.py
In line 294 the function name should be update_channel.
Someone changed the name to update_channels and now it doesn't work

**Comment by lamblin** [comment]
Right, `update_channel` was changed to `update_channels` almost everywhere, but that instance did not get changed.
Could you submit a pull request to change that line to `update_channels?
Otherwise, @daemonmaker, could you take care of that?

**Comment by daemonmaker** [comment]
The fix is in PR #1526 @lamblin.

**Comment by lamblin** [comment]
Fixed in #1526.

**Comment by lamblin** [comment]
Thanks!
