### ISSUE TITLE
SVHN bugs

### ISSUE THREAD

**Issue by fishcorn** [lisa-lab/pylearn2#1532]
~~`which_set='splitted_train'` and `which_set='valid'` fail because `split_train_valid` returns [four values, not two](https://github.com/lisa-lab/pylearn2/blob/393a75583e20b7ec7a539bdde66eb06596afe90d/pylearn2/datasets/svhn.py#L238-239). There's an easy fix, which is to simply turn the first two as a tuple and the last two as a tuple, because `split_train_valid` used to do this and apparently [the relevant code still expects this](https://github.com/lisa-lab/pylearn2/blob/393a75583e20b7ec7a539bdde66eb06596afe90d/pylearn2/datasets/svhn.py#L248).~~

Also, [this](https://github.com/lisa-lab/pylearn2/blob/393a75583e20b7ec7a539bdde66eb06596afe90d/pylearn2/datasets/svhn.py#L260-261) looks totally suspicious and I suspect that `which_set='train_all'` has incorrect labels.

**Comment by lamblin** [comment]
First part was fixed in #1371, thanks to @sandeepkbhat.
The second part is indeed suspicious.

**Comment by fishcorn** [comment]
I saw that, but it looks like it got merged away or something -- it's not in master ([current link](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/datasets/svhn.py#L238-239) as of the time of this comment).

**Comment by lamblin** [comment]
I just merged it, so the first part should be fixed now.
For the second part, I opened #1535.
