### ISSUE TITLE
Missing download file in tutorials

### ISSUE THREAD

**Issue by NexYY** [lisa-lab/pylearn2#1562]
Hi,

after failing with the tutorial I realized it isn't possible to accomplish the pylearn2 tutorial (http://deeplearning.net/software/pylearn2/tutorial/) as the first command "python make_dataset.py" will always fail due a exception called from the /scripts/tutorials/cifar10.py class.

The exception says you should run the "pylearn2/scripts/datasets/download_cifar10.sh" first to download cifar10, however this file does not exist anymore.

The exception also says that as an alternative you can just download cifar-10 manually, however newbies (for those who will use the tutorial) will also fail here, as without looking into the code they will not know that they have to wrap the cifar10 files into a "cifar10/cifar-10-batches-py" directory structure, which does differ from the usually just "cifar-10-batches-py" cifar10 structure.

I described the issue at stackoverflow: http://stackoverflow.com/questions/33623956/pylearn2-path-variable

**Comment by nouiz** [comment]
The download script still exist:

https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/scripts/datasets/download_cifar10.sh

I don't know why you don't find it, but I'll close the issue as it is still in the master of Pylearn2.

**Comment by NexYY** [comment]
It isn't here where it should be:

https://github.com/lisa-lab/pylearn2/tree/master/pylearn2/datasets

**Comment by dwf** [comment]
It's in scripts/, where all the other scripts are.
