### ISSUE TITLE
Invalid security certificate error 

### ISSUE THREAD

**Issue by Sentient07** [lisa-lab/pylearn2#1563]
When i tried downloading the dataset manually from the website, http://www.cs.utoronto.ca/~kriz/cifar.html , I get an invalid security certificate error.

**Comment by dwf** [comment]
Try https://www.cs.toronto.edu/~kriz/cifar.html

They probably have a certificate that is valid for *.toronto.edu but not *.utoronto.ca (they point to the same thing).

**Comment by Sentient07** [comment]
Yeah. Got it. Thanks! :+1:

**Comment by dwf** [comment]
If we refer to the other URL somewhere, a PR would be welcome.
