### ISSUE TITLE
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``samples``

### ISSUE THREAD

**Issue by nathaliascheltinga** [lisa-lab/pylearn2#1595]
I am trying to run Conifer using pytables but when I run
`python conifer.py call --input analysis.hdf5 --output calls.txt`
what I get is 
`tables.exceptions.NoSuchNodeError: group / does not have a child named samples`
How can i solve this?

**Comment by lamblin** [comment]
I think you have the wrong repo.
Did you mean to open that issue in https://github.com/PyTables/PyTables?
