### ISSUE TITLE
Use stuff in pylearn2.datasets.exc to make skippable unit tests for datasets

### ISSUE THREAD

**Issue by goodfeli** [lisa-lab/pylearn2#291]
In particular, should test FoveatedNORB. It was broken when I wanted to use it this week.

- [x] Avicenna
- [x] cifar100
- [x] CosDatast
- [x] NORBSmall
- [x] FoveatedNorb
- [x] MNISTPlus
- [x] hepatitis
- [x] icml07
- [x] iris
- [x] ocr
- [x] retina
- [x] stl10
- [ ] svhn (Mehdi)

**Comment by lamblin** [comment]
@memimo Can you check the checkboxes for the datasets that have tests?

**Comment by memimo** [comment]
I'm closing this ticket, since SVHN is dependent on the new hdf5 format or possibly fuel.
