### ISSUE TITLE
Detect out-of-date theano and raise warning or error as needed

### ISSUE THREAD

**Issue by goodfeli** [lisa-lab/pylearn2#313]
A lot of pylearn2 features require bleeding-edge theano. This will probably always be the case because we often develop new Theano features specifically in order to support new pylearn2 features. This is a common source of confusion for people setting up pylearn2, e.g.
https://www.kaggle.com/c/challenges-in-representation-learning-the-black-box-learning-challenge/forums/t/4480/pylearn2-install/24483#post24483
We should set up some way of detecting if theano is sufficiently up to date and displaying an error message if it is not.

@lamblin proposes the following plan:
- Define a custom Exception subclass for that, that prints this error message
- Get the latest released version of Theano (0.6rc3), not the bleeding edge one (can be done by `git checkout rel-0.6rc3`)
- Run pylearn2's test suite, and see which tests are failing because of Theano
- For each of these failures, add in the actual pylearn2 code (not the code of the test!) a check for Theano's version (or the presence of the feature that is needed), and raise the Exception defined above if needed
- In the end, all of the failures in the test suite should be because of this exception

**Comment by lamblin** [comment]
Correctly implementing that would require that we can automatically detect the first time Pylearn2 uses a new feature of Theano, or to automatically detect how out-of-date the installed version of Theano is.
This does not seem feasible atm.
