### ISSUE TITLE
termination_criterion.Or broken?

### ISSUE THREAD

**Issue by capybaralet** [lisa-lab/pylearn2#720]
When I use this termination criterion with max_epochs = 2 (500), it runs for 12 (510) epochs.  For some reason it seems like the N: 10 is being added to the epoch counter.  I haven't trained long enough for the MonitorBased one to trigger, I think, so I don't know what it is doing.

                   termination_criterion: !obj:pylearn2.termination_criteria.Or {
                                              criteria: [!obj:pylearn2.termination_criteria.MonitorBased {
                                                             channel_name: 'valid_objective',
                                                             prop_decrease: 0.005,
                                                             N: 10
                                                         },
                                                         !obj:pylearn2.termination_criteria.EpochCounter {
                                                                                    max_epochs: %(max_epochs)i
                                                         }]
                   },

**Comment by lamblin** [comment]
The decision was taken in the comments of #1311: rename termination_criterion into continuation_criterion.
I've opened #1405 explaining that solution, let's keep only that one open.
